# -*- coding: utf-8 -*-
"""Project 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xDYzKSEF8BFXRadHSmqRiem3p73J24jB

firts things first, we have to upload pandas(the python library for data frames and manipulation), and matplotlib(to plot our visualizations)
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

"""Now we have to assign a variable to our dataset, this will be oc(short for crime occurances)"""

oc = pd.read_csv('/content/drive/MyDrive/Datasets/Occurrence_-4324496069323609111.csv')

"""and here I remove the null values, and replace them with a much cleaner no"""

oc.fillna('no',inplace = True)

oc

"""now we want to set a filter, we are only going to be looking at the crime reports in Vaughan"""

filt = oc['Municipality'] == 'Vaughan'

"""let's take a look at the data from Vaughan"""

df = oc.loc[filt]
df

"""now that we have filtered all the reports that are in vaughan we can now delve down deeper into the dataset, and look specifically into the occurence types, we can count that and look at that in a series"""

o_type = df['Occurrence Type'].value_counts()
o_type

"""This is all of the types of crime reports that have been reported

the data has already been sorted, but we can gather some more insights
"""

o_type.describe()

"""25 diffrent types of reports, mininum for a type was 5 occurrences, maximum is 5275 reports for an occurence, and the mean amount of reports for an occurence is 834.28 while the median is 361. clearly the outliers are skewing the mean significantly. Is there more data we can gather? YES there is"""

lo_type = df.groupby(df['Location Code'])
lo_data = lo_type['Location Code'].value_counts()
lo_data.sort_values(ascending=False,inplace = True)
lo_data.drop('no', inplace = True)
lo_data

"""here is the location code for all of the occurences, as we can see The most of them happen at businesses, and the least happen outdoors. we can find the percentages of each as well"""

total_num = lo_data.sum()
lo_p = lo_data / total_num
lo_ = 'percentage(in decimal)'
lop = pd.DataFrame({'count':lo_data, 'total_percentage':lo_p})
lop

"""here is the data represented by its count, and by its coresponding percentage, ~ 45% of the occurences occur in busniness, ~32% in residences and ~23% of occurences happen outdoors

we can make it even more detailed and make a bar graph
"""

catagory = lop.index
values = lop['total_percentage']
plt.pie(values, labels = catagory, autopct = '%1.1f%%')
plt.title('percentage of occurences by location')

"""We can also make a graph representing the percantage of a specific report type, given that a report has occured"""

cat = o_type.index
op = o_type / o_type.sum()
val = op
plt.barh(cat, val ,edgecolor = 'black')
plt.title('percentage of occurences by type')
plt.xlabel('percentage(in decimals)')
plt.ylabel(' occurrence type')

"""horizontal bar graph was chosen due to there being a lot of occurence types but here is the data.

Now that we have gotten some basic analytics done, lets answer an interesting question. What will the thefts under 5000$ look like in the next coming years

for starters we can map this out on a time-series plot, but that'll require some data cleaning and filtering from our dataset.
"""

lg = pd.to_datetime(df['Occurrence Date'],format = '%Y-%m-%d')

df['Year_Month'] = lg.dt.to_period('M')

df.groupby('Year_Month')

falt = df['Occurrence Type'] == 'Theft Under $5000'

gf = df.loc[falt]

gr1 = gf['Occurrence Type'].value_counts()

gf.set_index(np.arange(len(gf)),inplace = True)
gf.groupby(gf['Year_Month'])
gf

af = pd.pivot_table(
    df,
    values='Occurrence Type',
    index='Year_Month',
    columns= falt,
    aggfunc='count'
)
af

gf = af.drop(False, axis = 1)
gf['Num of Theft below 5000$'] = gf[True]
gf.drop(True, axis = 1, inplace = True)
gf.drop('2026-07', axis=0, inplace=True)

fig = plt.figure(figsize=(17,6))
sns.scatterplot(x = gf.index.astype(str), y = 'Num of Theft below 5000$', data = gf,)

"""looking at the graph we can also apply the mean and median,this will give us some insight"""

gf.agg(['mean','median'])

"""we can go one step further and ask ourselves, 'is there a relationship between the times of the crime, do more occurences happen during the night. we obviously would assume so, but how true could this be? well, lets first plot it out and then we can see if there is a relationship.

for a more accurate overview we'll use all of york region since it contains more data. We can also start by making a simple count plot that tracks the count of occurences given the time.
"""

oc['Time'] = pd.to_datetime(df['Time'], format='%H:%M')
oc['Time'] = oc['Time'].dt.hour

fig, ax = plt.subplots(figsize=(17,6))
yt =sns.countplot(x = 'Time', data = oc, color = 'red', ax=ax,)

"""now that we have the data in front of us, some basic EDA tells us most occured during midnight and the least occured during 6am."""